### ISSUE TITLE
Sharepoint Preprocessor

### ISSUE THREAD

**Issue by mlaguren** [Cell-Checker/cell-checker#14]
**Is your feature request related to a problem? Please describe.**
As part of the framework,
There needs to be a mechanism to download files from external sources,
So that comparisons can be made between source/target

**Describe the solution you'd like**
Using Durable Rules, we can create a rule set called Preprocessor. The Preprocessor serves as an initial step in the cell checking process, tasked with the retrieval and preliminary preparation of data files from various external storage locations. The sharepoint preprocessor will retrieve the file from a sharepoint folder and bring it locally to cell checker.

**Describe alternatives you've considered**
Integrating a sharepoint command with the source directive in the cell checker test would not allow for proper scaling as more preprocessor functions may occur, besides grabbing files from sources. Renaming a file could be a preprocessor step for example.

**Comment by paramveerbright1982** [comment]
PR - https://github.com/Cell-Checker/cell-checker/pull/17
